site_name: pyvrft
site_description: Virtual Reference Feedback Tuning Toolbox
site_author: Diego Eckhard
repo_url: https://github.com/datadrivencontrol/pyvrft
repo_name: datadrivencontrol/pyvrft
site_url: https://pyvrft.net/

theme:
  name: material
  palette:
    primary: red
    accent: red
  features:
    - navigation.sections
    - search.suggest
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Quick Start: quickstart.md
      - Basic Concepts: basic-concepts.md
  - Examples: examples.md
  - API Reference: api.md
  - Citation: citation.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - toc:
      permalink: true
